services:
  - type: web
    name: izumi-v2
    env: node
    branch: main
    repo: https://github.com/sataniceypz/Izumi-v2.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: 𝐄𝐘𝐏𝐙 ; 𝗜𝗭𝗨𝗠𝗜-𝗫𝗗 ; https://i.imgur.com/Uc0uIkO.jpeg
      - key: PREFIX
        value: ^[.]
      - key: WORK_TYPE
        value: private
      - key: STICKER_PACKNAME
        value: 𝗜𝗭𝗨𝗠𝗜 𝗫𝗗;𝐄𝐘𝐏𝐙
      - key: AUDIO_DATA
        value: 𝐄𝐘𝐏𝐙 ; 𝗜𝗭𝗨𝗠𝗜-𝗫𝗗 ; https://i.imgur.com/Uc0uIkO.jpeg
      - key: SUDO
        value: false
      - key: ALLWAYS_ONLINE
        value: false
      - key: CAPTIOM
        value: 𝗜𝗭𝗨𝗠𝗜-𝗫𝗗
      - key: DATABASE_URL
        sync: false
